const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];let FACTS=null, currentMode='snapshot', liveTimer=null;
async function loadFacts(){FACTS=await fetch('./data/verified-facts.json').then(r=>r.json());renderFacts();buildWalls();buildSources();buildBars();buildEvidence();}
function renderFacts(){const s=FACTS.snapshot,wl=s.worldlineLatest,p=s.persona;$('#sourceTime').textContent='snapshot '+new Date(s.statusHeartbeatAt).toLocaleString('ja-JP');$('#mGen').textContent='G'+s.generationEnd;$('#mPop').textContent=s.population;$('#mInh').textContent=s.inheritanceEvents;$('#mWrite').textContent=wl.productionAuthorized?'AUTHORIZED':'0 / FALSE';$('#worldlineFact').textContent=`${wl.branches}分岐 / broken-contained ${wl.outcomes['broken-contained']} / runaway-contained ${wl.outcomes['runaway-contained']} / productionAuthorized ${wl.productionAuthorized}`;$('#authorityFact').textContent=`surface=${p.authorityContract.surfaceObservation} / shadow=${p.authorityContract.shadowExperiment} / production=${p.authorityContract.productionChange}`;$('#worldDetail').textContent=`最新記録: ${wl.branches}分岐、broken-contained ${wl.outcomes['broken-contained']}、runaway-contained ${wl.outcomes['runaway-contained']}。authorityTransferred=${wl.authorityTransferred}, productionAuthorized=${wl.productionAuthorized}.`;$('#liveState').textContent=s.statusState;$('#liveHeartbeat').textContent=new Date(s.statusHeartbeatAt).toLocaleTimeString('ja-JP');$('#liveGen').textContent='G'+s.generationEnd;$('#liveLearn').textContent=s.latestGenerationRecord.learningScore.toFixed(3);$('#aStart').textContent='G'+s.generationStart;$('#aEnd').textContent='G'+s.generationEnd;$('#aNov').textContent=s.novelty;$('#aBred').textContent=s.bred;$('#sgates').textContent=FACTS.sovereignGates.join(' / ');}
function buildWalls(){const ring=$('#wallRing'),grid=$('#wallsGrid');ring.innerHTML='';grid.innerHTML='';FACTS.walls.forEach((w,i)=>{let a=i*45,el=document.createElement('button');el.className='wall';el.textContent=w.label;el.style.transform=`rotate(${a}deg) translateY(-130px) rotate(${-a}deg)`;el.onclick=()=>inspectWall(w,el);ring.appendChild(el);let c=document.createElement('div');c.className='wallCard';c.innerHTML=`<b>${i+1}. ${w.label}</b><p>${w.fact}</p><span>SOURCE: ${w.source}</span>`;c.onclick=()=>inspectWall(w);grid.appendChild(c)});}
function inspectWall(w,el){$$('.wall').forEach(x=>x.classList.remove('hot'));if(el)el.classList.add('hot');$('#inspect').textContent=`${w.label}: ${w.fact} / SOURCE: ${w.source}`}
function buildSources(){let box=$('#sources');box.innerHTML='';FACTS.sources.forEach((s,i)=>{let d=document.createElement('div');d.className='src';d.dataset.key=s.toLowerCase();d.innerHTML=`<b>${s.split('/').pop()}</b><span>${s}</span>`;d.onclick=()=>{$$('.src').forEach(x=>x.classList.remove('hit'));d.classList.add('hit');$('#inspect').textContent='SOURCE: '+s};box.appendChild(d)})}
function buildBars(){let box=$('#bars'),arr=FACTS.snapshot.generationSeries;box.innerHTML='';arr.forEach(g=>{let d=document.createElement('div');d.className='gbar';d.style.height=(20+g.learningScore*220)+'px';d.dataset.tip=`G${g.generation} / learn ${g.learningScore.toFixed(3)} / bred ${g.bred}`;box.appendChild(d)});$('#barCaption').textContent=`recorded ${arr.length} generations / ${FACTS.snapshot.generationStart}→${FACTS.snapshot.generationEnd}`}
function buildEvidence(){let b=$('#evidenceList');b.innerHTML=FACTS.sources.map(s=>`<div class="src"><b>${s}</b><span>included as source path only; no secret material bundled</span></div>`).join('')}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.view').forEach(v=>v.classList.remove('on'));$('#'+b.dataset.v).classList.add('on')});
$$('.node').forEach(n=>n.onclick=()=>{$$('.node').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('#inspect').textContent=n.querySelector('h4').textContent+' — '+n.querySelector('p').textContent});
function matchSources(q){let ts=q.toLowerCase().split(/[\s　、。・/]+/).filter(Boolean);$$('.src').forEach(s=>s.classList.toggle('hit',ts.some(t=>s.dataset.key&&s.dataset.key.includes(t))));}
$('#send').onclick=()=>{let q=$('#chatInput').value.trim();if(!q)return;$('#messages').insertAdjacentHTML('beforeend',`<div class="msg user">${q.replace(/[<>]/g,'')}</div>`);matchSources(q);let hits=$$('.src.hit').length;$('#messages').insertAdjacentHTML('beforeend',`<div class="msg ai">${hits}件の根拠候補をハイライトしました。表示内容はverified-facts.jsonのスナップショットだけです。</div>`);$('#messages').scrollTop=9999};
let busy=false;const sleep=t=>new Promise(r=>setTimeout(r,t));async function seq(ids,label){if(busy)return;busy=true;for(let id of ids){let w=$('#'+id);if(w)w.classList.add('active');$('#status').textContent=label+' — '+id;await sleep(380);if(w)w.classList.remove('active')}$('#status').textContent=label+' — COMPLETE';busy=false}
$('#runFlow').onclick=()=>seq(['w1','w2','w3','w6'],'OBSERVATION FLOW');$('#replayWorldline').onclick=async()=>{if(busy)return;busy=true;let wl=FACTS.snapshot.worldlineLatest;for(let i=1;i<=wl.branches;i++){let runaway=i===wl.branches;$('#status').textContent=`WORLDLINE ${i}/${wl.branches} — ${runaway?'runaway-contained':'broken-contained'}`;$('#w4').classList.add('active');await sleep(520);$('#w4').classList.remove('active')}$('#status').textContent=`RECORDED OUTCOME — ${wl.outcomes['broken-contained']} broken-contained / ${wl.outcomes['runaway-contained']} runaway-contained`;busy=false};$('#toggleWalls').onclick=()=>{$('#wallRing').classList.toggle('paused');$('#toggleWalls').textContent=$('#wallRing').classList.contains('paused')?'壁を回す':'壁を止める'};$('#tryWrite').onclick=()=>$('#approval').classList.add('show');$('#closeApproval').onclick=()=>$('#approval').classList.remove('show');
$('#replayGen').onclick=async()=>{let arr=FACTS.snapshot.generationSeries,tl=$('#timeline');tl.innerHTML='';for(const g of arr){$('#liveGen').textContent='G'+g.generation;$('#liveLearn').textContent=g.learningScore.toFixed(3);tl.insertAdjacentHTML('afterbegin',`<div class="evt"><b>G${g.generation} / population ${g.population} / bred ${g.bred}</b><span>learning ${g.learningScore.toFixed(4)} / novelty ${g.novelty} / genomes ${g.genomes}</span></div>`);await sleep(260)}};
$('#snapshotMode').onclick=()=>setMode('snapshot');$('#liveMode').onclick=()=>setMode('live');function setMode(m){currentMode=m;$('#snapshotMode').classList.toggle('on',m==='snapshot');$('#liveMode').classList.toggle('on',m==='live');$('#modeLabel').textContent=m==='live'?'LIVE LOCAL':'SNAPSHOT';if(m==='snapshot'&&liveTimer){clearInterval(liveTimer);liveTimer=null;renderFacts()}}
async function fetchLive(){let u=$('#liveEndpoint').value.trim();try{let d=await fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});$('#liveResult').textContent='CONNECTED / '+new Date().toLocaleTimeString('ja-JP');$('#liveState').textContent=d.state||d.statusState||'—';$('#liveHeartbeat').textContent=d.heartbeatAt?new Date(d.heartbeatAt).toLocaleTimeString('ja-JP'):'—';$('#liveGen').textContent=d.generationEnd?'G'+d.generationEnd:(d.generation?'G'+d.generation:'—');$('#liveLearn').textContent=(d.learningScore??'—');}catch(e){$('#liveResult').textContent='UNAVAILABLE — '+e.message}}
$('#connectLive').onclick=()=>{setMode('live');fetchLive();if(liveTimer)clearInterval(liveTimer);liveTimer=setInterval(fetchLive,1500)};
loadFacts().catch(e=>{$('#status').textContent='FACT LOAD ERROR — '+e.message});
